

# This file was *autogenerated* from the file particle_systems.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_0 = Integer(0); _sage_const_p1 = RealNumber('.1'); _sage_const_1 = Integer(1); _sage_const_p5 = RealNumber('.5'); _sage_const_0p1 = RealNumber('0.1'); _sage_const_5 = Integer(5); _sage_const_50 = Integer(50); _sage_const_100 = Integer(100); _sage_const_25 = Integer(25); _sage_const_20 = Integer(20); _sage_const_51 = Integer(51); _sage_const_57 = Integer(57); _sage_const_250 = Integer(250); _sage_const_30 = Integer(30)#To Run
#sage particle_systems.sage
import random
from sage.plot.plot3d.shapes import *
from sage.plot.plot3d.shapes2 import Line
from sage.plot.plot3d.shapes2 import line3d

linear_rotation = "linear rotation"
linear_attractor = "linear attractor"
linear_rotation_with_attractor = "linear rotation with attractor"
brownean = "brownean"
browneanSpherical = "browneanSpherical"
browneanCylindrical = "browneanCylindrical"
browneanManifold = "browneanManifold"

class particle(object):
    """a particle"""
    def __init__(self, **kwargs):
        self.dimensions = kwargs.get("dimensions")
        self.forcefields = kwargs.get("forcefields")
        self.color = kwargs.get("color")
        self.history = []
        for forcefield in self.forcefields:
            forcefield.register_particle(self)

    def spherical_normalize(self):
        x = self.dimensions["x"]
        y = self.dimensions["y"]
        z = self.dimensions["z"]
        radius = self.dimensions["r"]
        rnorm=sqrt(x**_sage_const_2 +y**_sage_const_2 +z**_sage_const_2 )/radius
        self.dimensions["x"] = x/rnorm
        self.dimensions["y"] = y/rnorm
        self.dimensions["z"] = z/rnorm

    def cylindrical_normalize(self):
        x = self.dimensions["x"]
        y = self.dimensions["y"]
        z = self.dimensions["z"]
        radius = self.dimensions["r"]
        rnorm = sqrt(x**_sage_const_2 +y**_sage_const_2 )/radius
        self.dimensions["x"] = x/rnorm
        self.dimensions["y"] = y/rnorm
        self.dimensions["z"] = z

    def manifold_normalize(self): #fixme
        x = self.dimensions["x"]
        y = self.dimensions["y"]
        z = self.dimensions["z"]
        #minimize distance to a given manifold. (Fixme)
        x_new = x
        y_new = y
        z_new = z
        self.dimensions["x"] = x_new
        self.dimensions["y"] = y_new
        self.dimensions["z"] = z_new

    def normalize(self):
        if False:
            self.spherical_normalize()
        elif True:
            self.cylindrical_normalize()
        elif False:
            self.manifold_normalize()

    def move(self):
        self.history.append({"x":self.dimensions["x"], "y":self.dimensions["y"], "z":self.dimensions["z"]})
        for field in self.forcefields:
            self.dimensions.update(field.perturb(self.dimensions))
        self.normalize()

class field(object):
    """a field object"""
    def __init__(self):
        self.particles = []

    def deform(self):
        pass

    def register_particle(self, particle):
        self.particles.append(particle)

    def force_at_location(self, dimensions):
        return {"vx":_sage_const_0 , "vy":_sage_const_0 , "vz":_sage_const_0 }

    def perturb(self, dimensions):
        newdimensions = {}
        newdimensions.update(dimensions)
        force_at_location_freeze=self.force_at_location(dimensions)
        for xi, vxi in [("x","vx"), ("y","vy"), ("z", "vz")]:
            if xi in dimensions and vxi in dimensions:
                xi_new = dimensions[xi] + dimensions[vxi]
                newdimensions[xi] = xi_new
                vxi_new = dimensions[vxi]+force_at_location_freeze.get(vxi)
                newdimensions[vxi] = vxi_new
        return newdimensions

class linearRotationField(field):
    """linear rotation"""
    def force_at_location(self, dimensions):
        dt = _sage_const_p1 
        return {"vx":-dimensions.get("y")*dt, "vy":dimensions.get("x")*dt, "vz":_sage_const_0 }

class linearRotationFieldWithAttractor(field):
    """linear rotation with attractor"""
    def force_at_location(self, dimensions):
        dt = _sage_const_p1 
        dr = _sage_const_1 /(dimensions.get("x")**_sage_const_2 +dimensions.get("y")**_sage_const_2 )**_sage_const_p5 
        return {"vx":(-dimensions.get("y")-_sage_const_2 *dimensions.get("x"))*dt*dr, "vy":(dimensions.get("x")-_sage_const_2 *dimensions.get("y"))*dt*dr, "vz":_sage_const_0 }

class linearAttractor(field):
    """linear rotation with attractor"""
    def force_at_location(self, dimensions):
        dt = _sage_const_p1 
        dr = _sage_const_1 /(dimensions.get("x")**_sage_const_2 +dimensions.get("y")**_sage_const_2 )**_sage_const_p5 
        return {"vx":(-dimensions.get("x"))*dt*dr, "vy":(-dimensions.get("y"))*dt*dr, "vz":_sage_const_0 }


class browneanField(field):
    """brownean"""
    def force_at_location(self, dimensions):
        dt = _sage_const_p1 
        dx = random.gauss(_sage_const_0 ,_sage_const_1 )
        dy = random.gauss(_sage_const_0 ,_sage_const_1 )
        dz = random.gauss(_sage_const_0 ,_sage_const_1 )
        return {"vx":dx*dt, "vy":dy*dt, "vz":dz*dt}

class browneanSphericalField(field):
    """brownean spherical"""
    def force_at_location(self, dimensions):
        dt = _sage_const_0p1 
        sigma=_sage_const_5 
        dx = random.gauss(_sage_const_0 ,sigma)
        dy = random.gauss(_sage_const_0 ,sigma)
        dz = random.gauss(_sage_const_0 ,sigma)
        x = dimensions.get("x")
        y = dimensions.get("y")
        z = dimensions.get("z")
        vx = dimensions.get("vx")
        vy = dimensions.get("vy")
        vz = dimensions.get("vz")
        xperturb = dx*dt
        yperturb = dy*dt
        zperturb = dz*dt
        #also need to cancel the radius by adding this: r/|r|-r
        rnorm = sqrt(x**_sage_const_2  + y**_sage_const_2  + z**_sage_const_2 )
        print(f"rnorm={rnorm}")
        xnew = _sage_const_50 *xperturb/rnorm
        ynew = _sage_const_50 *yperturb/rnorm
        znew = _sage_const_50 *zperturb/rnorm
        return {"vx":dx-vx, "vy":dy-vy, "vz":dz-vz}

class browneanCylindricalField(field):
    """brownean cylindrical"""
    def force_at_location(self, dimensions):
        dt = _sage_const_0p1 
        sigma=_sage_const_5 
        dx = random.gauss(_sage_const_0 ,sigma)
        dy = random.gauss(_sage_const_0 ,sigma)
        dz = random.gauss(_sage_const_0 ,sigma)
        x = dimensions.get("x")
        y = dimensions.get("y")
        z = dimensions.get("z")
        vx = dimensions.get("vx")
        vy = dimensions.get("vy")
        vz = dimensions.get("vz")
        xperturb = dx*dt
        yperturb = dy*dt
        zperturb = dz*dt
        #also need to cancel the radius by adding this: r/|r|-r
        rnorm = sqrt(x**_sage_const_2  + y**_sage_const_2 )
        print(f"rnorm={rnorm}")
        xnew = _sage_const_50 *xperturb/rnorm
        ynew = _sage_const_50 *yperturb/rnorm
        znew = zperturb
        return {"vx":dx-vx, "vy":dy-vy, "vz":dz-vz}

class browneanManifoldField(field):
    """brownean manifold"""
    def force_at_location(self, dimensions):
        dt = _sage_const_0p1 
        sigma=_sage_const_5 
        dx = random.gauss(_sage_const_0 ,sigma)
        dy = random.gauss(_sage_const_0 ,sigma)
        dz = random.gauss(_sage_const_0 ,sigma)
        x = dimensions.get("x")
        y = dimensions.get("y")
        z = dimensions.get("z")
        vx = dimensions.get("vx")
        vy = dimensions.get("vy")
        vz = dimensions.get("vz")
        xperturb = dx*dt
        yperturb = dy*dt
        zperturb = dz*dt
        #get info from manifold curvature.
        xnew = xperturb
        ynew = yperturb
        znew = zperturb
        return {"vx":dx-vx, "vy":dy-vy, "vz":dz-vz}

class flatField(field):
    """flat field"""
    pass

class forceFieldFactory(object):
    """Creates a field"""
    def __init__(self, **kwargs):
        self.forcefield_type = kwargs.get("forcefield_type")

    def newField(self):
        if self.forcefield_type == linear_rotation:
            return linearRotationField()
        elif self.forcefield_type == linear_rotation_with_attractor:
            return linearRotationFieldWithAttractor()
        elif self.forcefield_type == brownean:
            return browneanField()
        elif self.forcefield_type == browneanSpherical:
            return browneanSphericalField()
        elif self.forcefield_type == browneanCylindrical:
            return browneanCylindricalField()
        elif self.forcefield_type == browneanManifold:
            return browneanManifoldField()
        else:
            return flatField()

class particleFactory(object):
    def __init__(self, **kwargs):
        self.forcefields = kwargs.get("forcefields")
        self.timeout = kwargs.get("timeout")
        self.color = kwargs.get("color","blue")
        self.radius = kwargs.get("radius",_sage_const_50 )
        self.forcefield_type_list = kwargs.get("forcefield_type_list")

    def newParticle(self):
        dimensions = {"x":random.random()*_sage_const_100 -_sage_const_50 , "y":random.random()*_sage_const_100 -_sage_const_50 , "z":random.random()*_sage_const_100 -_sage_const_50 , "vx":_sage_const_0 , "vy":_sage_const_0 , "vz":_sage_const_0 , "m":_sage_const_1 , "r":self.radius}    
        mote = particle(dimensions=dimensions, forcefields=self.forcefields, color=self.color)
        return mote

class particle_systems(object):
    """Shows Particle Systems"""
    particle_list = []
    field_list = []

    def visualize_frame(self):
        """Visualize a particle system"""
        frame = Graphics()
        frame3d = sage.plot.plot3d.base.Graphics3d()
        frame.axes(False)
        frame3dtrail = sage.plot.plot3d.base.Graphics3d()
        for particle in self.particle_list:
            x = particle.dimensions.get("x")
            y = particle.dimensions.get("y")
            z = particle.dimensions.get("z", _sage_const_0 )
            color=particle.color
            size = particle.dimensions.get("m")
            d = disk((x,y), size, (_sage_const_0 , _sage_const_2 *pi), color=color)
            d.axes(False)
            frame += d
            sphere3d = sage.plot.plot3d.shapes2.sphere(center=(x,y,z), size=size, color=color, aspect_ratio=[_sage_const_1 ,_sage_const_1 ,_sage_const_1 ])
            frame3d += sphere3d
            print(f"particle.history = {particle.history}")
            eventlist = [(event.get("x"), event.get("y"), event.get("z")) for event in particle.history][_sage_const_1 :]
            print(f"len(eventlist) = {len(eventlist)}")
            if len(eventlist) > _sage_const_1 :
                zipped_eventlist = [eventpair for eventpair in zip(eventlist, [(_sage_const_0 ,_sage_const_0 ,_sage_const_0 )]+eventlist)][_sage_const_1 :]
                # print(eventlist)
                b = line3d(eventlist, thickness=_sage_const_1 , opacity=_sage_const_1 , aspect_ratio=_sage_const_1 , color=color)
                frame3dtrail+=b
                # print(b)
                # b = line(eventlist)
        frame.axes(False)
        return frame,frame3d,frame3dtrail

    def __init__(self, field_config_dict, particle_config_list):
        """Initializes an object"""
        for profile in field_config_dict:
            forcefield_type = field_config_dict.get(profile).get("forcefield_type", linear_rotation)
            force_field_factory = forceFieldFactory(forcefield_type=forcefield_type)
            forcefield = force_field_factory.newField()
            field_config_dict[profile]["forcefield"] = forcefield

        for profile in particle_config_list:
            forcefield_type_list = profile.get("forcefield_type_list")
            timeout = profile.get("timeout", _sage_const_1 )
            number_particles = profile.get("number_particles", _sage_const_100 )
            color = profile.get("color", "blue")
            radius = profile.get("radius",_sage_const_50 )
            print(f"forcefield_type_list={forcefield_type_list}")
            forcefields = [field_config_dict.get(forcefield_type).get("forcefield") for forcefield_type in forcefield_type_list]
            particle_factory = particleFactory(forcefields=forcefields, timeout=timeout, color=color, radius=radius, forcefield_type_list=forcefield_type_list)
            for i in range(_sage_const_0 , number_particles):
                particle = particle_factory.newParticle()
                self.particle_list.append(particle)

    def act(self):
        for particle in self.particle_list:
            particle.move()
        for field in self.field_list:
            field.deform()

def main():
    #plotname="test_3nsov2023"
    #plotname="brownean"
    #plotname="browneanSpherical"
    #plotname="jake"
    plotname="cylindrical_test"
    #plotname="manifold_test"
    forcefield_config = {linear_rotation : {"forcefield_type" : linear_rotation}, linear_attractor : {"forcefield_type" : linear_attractor}, linear_rotation_with_attractor : {"forcefield_type" : linear_rotation_with_attractor}, brownean : {"forcefield_type" : brownean}, browneanSpherical : {"forcefield_type" : browneanSpherical}}
    forcefield_config = {browneanSpherical : {"forcefield_type" : browneanSpherical}}
    forcefield_config = {browneanCylindrical : {"forcefield_type" : browneanCylindrical}}
    #forcefield_config = {browneanManifold : {"forcefield_type" : browneanManifold}}
    if plotname == "test_3nov2023":
        particle_config = [{"forcefield_type_list":[linear_rotation], "timeout":_sage_const_1 , "number_particles":_sage_const_100 , "color":"blue"}, {"forcefield_type_list":[linear_rotation_with_attractor], "timeout":_sage_const_1 , "number_particles":_sage_const_100 , "color":"blue"}, {"forcefield_type_list":[linear_attractor], "timeout":_sage_const_1 , "number_particles":_sage_const_100 , "color":"blue"}]
    elif plotname == "brownean":
        particle_config = [{"forcefield_type_list":[brownean], "timeout":_sage_const_1 , "number_particles":_sage_const_100 , "color":"green"}]
    elif plotname == "browneanSpherical":
        particle_config = [
        {"forcefield_type_list":[browneanSpherical], "timeout":_sage_const_1 , "number_particles":_sage_const_25 , "color":"blue", "radius":_sage_const_50 },
        #{"forcefield_type_list":[browneanSpherical], "timeout":1, "number_particles":10, "color":"brown", "radius":52},
        {"forcefield_type_list":[browneanSpherical], "timeout":_sage_const_1 , "number_particles":_sage_const_20 , "color":"green", "radius":_sage_const_51 },
        {"forcefield_type_list":[browneanSpherical], "timeout":_sage_const_1 , "number_particles":_sage_const_5 , "color":"grey", "radius":_sage_const_57 }
        ]
    elif plotname == "jake":
        particle_config = [
        {"forcefield_type_list":[browneanSpherical], "timeout":_sage_const_1 , "number_particles":_sage_const_250 , "color":"pink", "radius":_sage_const_100 }
        ]
    elif plotname == "cylindrical_test":
        particle_config = [{"forcefield_type_list":[browneanCylindrical], "timeout":_sage_const_1 , "number_particles":_sage_const_20 , "color":"blue", "radius":_sage_const_50 },
                           {"forcefield_type_list":[browneanCylindrical], "timeout":_sage_const_1 , "number_particles":_sage_const_20 , "color":"yellow", "radius":_sage_const_30 }]
    elif plotname == "manifold_test":
        particle_config = [{"forcefield_type_list":[browneanManifold], "timeout":_sage_const_1 , "number_particles":_sage_const_20 , "color":"blue"}]
    ps = particle_systems(forcefield_config, particle_config)
    timesteps = _sage_const_100 
    frames = []
    frames3d = []
    frames_3dtrail=[]
    for i in range(_sage_const_0 ,timesteps):
        print(f"Timestep {i}/{timesteps}")
        ps.act()
        if i>_sage_const_1 :
            frame,frame3d,frame_3dtrail = ps.visualize_frame()
            frame.save(f"results/{plotname}/frame_{i}.png".format(i=i), xmin=-_sage_const_100 , xmax=_sage_const_100 , ymin=-_sage_const_100 , ymax=_sage_const_100 )
            frames.append(frame)
            frame3d.save(f"results/{plotname}/frame3d_{i}.png".format(i=i), xmin=-_sage_const_100 , xmax=_sage_const_100 , ymin=-_sage_const_100 , ymax=_sage_const_100 , zmin=-_sage_const_100 , zmax=_sage_const_100 )
            frames3d.append(frame3d)
            frame_3dtrail.save(f"results/{plotname}/frame3dtrail_{i}.png".format(i=i), frame=False, xmin=-_sage_const_100 , xmax=_sage_const_100 , ymin=-_sage_const_100 , ymax=_sage_const_100 , zmin=-_sage_const_100 , zmax=_sage_const_100 )
            frames_3dtrail.append(frame_3dtrail)
    print("animating frames...")
    animate(frames,xmin=-_sage_const_100 ,xmax=_sage_const_100 ,ymin=-_sage_const_100 , ymax=_sage_const_100 , axes=False).save(f'results/{plotname}/plots.gif')
    print("animating frames3d...")
    animate(frames3d, xmin=-_sage_const_100 , xmax=_sage_const_100 , ymin=-_sage_const_100 , ymax=_sage_const_100 , zmin=-_sage_const_100 , zmax=_sage_const_100 , axes=False, frame=False).save(f'results/{plotname}/plots3d.gif')
    print("animating frames_3dtrail...")
    animate(frames_3dtrail, xmin=-_sage_const_100 , xmax=_sage_const_100 , ymin=-_sage_const_100 , ymax=_sage_const_100 , zmin=-_sage_const_100 , zmax=_sage_const_100 , axes=False, frame=False).save(f'results/{plotname}/plots3dtrail.gif')
    #ps.visualize_movie(frames)

if __name__ == "__main__":
    main()

